# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4a2b2d8ce76e19f1a8b4bb7aed0bd9b8998edf1b5c5ef034f322bc6b6e258d64d1cc8f1a22d14c78d86489b46502a4ea41229dd5f09b79762a1675eb51eba40

test:
  secret_key_base: 2de1492a5bca5c57de8a75ced93b73ca5fe8fd7cf6f49b33fdae2d9a4c4835203b410b6fc25c44f38c2afb78555c017cb6750441b39de5ad236e05e0c332aaa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
